apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxboat-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: boxboat/hello-world-webapp
        ports:
        - containerPort: 8080
